version: '3.7'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - hosts:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - hosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  registry:
    image: registry:2
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${DOMAIN_NAME}.crt
      REGISTRY_HTTP_TLS_KEY: /certs/${DOMAIN_NAME}.key
    volumes:
      - registry:/var/lib/registry
      - certs:/certs
      - ./htpasswd:/auth/htpasswd
    restart: always

  cache-registry:
    image: registry:2
    restart: always
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      REGISTRY_STORAGE_DELETE_ENABLED: 1
      VIRTUAL_HOST: ${CACHE_DOMAIN_NAME}
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: ${CACHE_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${CACHE_DOMAIN_NAME}.crt
      REGISTRY_HTTP_TLS_KEY: /certs/${CACHE_DOMAIN_NAME}.key
    volumes:
      - cache-registry:/var/lib/registry
      - certs:/certs
      - ./htpasswd:/auth/htpasswd

volumes:
  registry:
  cache-registry:
  certs:
  hosts:
  html: