- hosts: default
  become: yes
  remote_user: root
  roles:
    - role: geerlingguy.docker
      vars:
        ansible_os_family: 'Debian'
        docker_edition: 'ce'
        docker_group: 'docker'
        docker_compose_version: '1.25.0'
    - role: ssh-user
    - role: add-swap

